name: projectmain
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.6
  file_picker: ^6.1.1
  firebase_auth: ^4.17.6
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.7
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  fluttertoast: ^8.2.4
  qr_code_scanner: ^1.0.1
  intl: ^0.19.0
  progress_dialog_null_safe: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/'
